# Generated by Django 2.1.7 on 2019-06-08 19:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import home.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='CodeDoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='CodeLamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='CodeSocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='CodeWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Датчики', max_length=100)),
                ('temperature', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.CodeCondition')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Дверь', max_length=100)),
                ('opened', models.BooleanField(default=False)),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.CodeDoor')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=168)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Лампа', max_length=100)),
                ('switched', models.BooleanField(default=False)),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.CodeLamp')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('type', models.CharField(default='1', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('version', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('image', models.FileField(default='', upload_to='')),
                ('components', models.CharField(default='', max_length=100)),
                ('other_img', models.FileField(default='', null=True, upload_to='')),
                ('description', models.CharField(default='', max_length=200)),
                ('license', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('token_1', models.CharField(default='', max_length=65)),
                ('token_2', models.CharField(default='', max_length=65)),
                ('email', models.EmailField(max_length=254)),
                ('tries_left', models.IntegerField(default=3)),
                ('expires', models.DateTimeField(default=datetime.datetime(2019, 6, 9, 19, 34, 31, 898918, tzinfo=utc))),
                ('confirm_token_1', models.CharField(default='', max_length=65)),
                ('confirm_token_2', models.CharField(default='', max_length=65)),
                ('code', models.IntegerField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Personalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pictures/', validators=[home.validators.validate_file_extension])),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Room', max_length=100)),
                ('house', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Home')),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Розетка', max_length=100)),
                ('switched', models.BooleanField(default=False)),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.CodeSocket')),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Окно', max_length=100)),
                ('opened', models.BooleanField(default=False)),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.CodeDoor')),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room')),
            ],
        ),
        migrations.AddField(
            model_name='lamp',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
        migrations.AddField(
            model_name='door',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
        migrations.AddField(
            model_name='condition',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
        migrations.AddField(
            model_name='codewindow',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
        migrations.AddField(
            model_name='codesocket',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
        migrations.AddField(
            model_name='codelamp',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
        migrations.AddField(
            model_name='codedoor',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
        migrations.AddField(
            model_name='codecondition',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
    ]
