# Generated by Django 2.1.7 on 2019-06-08 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 9, 19, 34, 53, 800364, tzinfo=utc)),
        ),
    ]
