# Generated by Django 2.1.7 on 2019-06-09 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190608_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Home'),
        ),
        migrations.AlterField(
            model_name='passwordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 5, 22, 7, 22035, tzinfo=utc)),
        ),
    ]
