# Generated by Django 2.1.7 on 2019-06-05 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190520_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 13, 21, 46, 50058, tzinfo=utc)),
        ),
    ]
